"use client";

import { useEffect, useState } from "react";
import { useApp } from "@/lib/app-context";
import { clearAlerts, getAlerts, useMounted } from "@/lib/store";
import { Bell, FileDown, Trash2, Mail, MessageSquare } from "lucide-react";

export default function AlertsPage() {
  const { t } = useApp();
  const mounted = useMounted();
  const [alerts, setAlerts] = useState<{ id: string; ts: number; sensorId: string; parameter: string; value: number; severity: "marginal" | "critical"; message: string }[]>([]);
  const [filter, setFilter] = useState<"all" | "marginal" | "critical">("all");

  useEffect(() => {
    if (!mounted) return;
    setAlerts(getAlerts());
    const id = window.setInterval(() => setAlerts(getAlerts()), 2000);
    return () => window.clearInterval(id);
  }, [mounted]);

  const filtered = alerts.filter((a) => filter === "all" || a.severity === filter);

  function exportCsv() {
    const header = ["ts", "sensorId", "parameter", "value", "severity", "message"];
    const rows = alerts.map((a) => [new Date(a.ts).toISOString(), a.sensorId, a.parameter, a.value, a.severity, a.message.replace(/,/g, ";")]);
    const csv = [header, ...rows].map((r) => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `aquapure-alerts-${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function shareWA(a: { message: string; ts: number; severity: "marginal" | "critical" }) {
    const text = encodeURIComponent(`AquaPure ${a.severity.toUpperCase()} - ${a.message} at ${new Date(a.ts).toLocaleString()}`);
    window.open(`https://wa.me/?text=${text}`, "_blank");
  }

  function mailto(a: { message: string; ts: number; severity: "marginal" | "critical" }) {
    const subject = encodeURIComponent(`AquaPure ${a.severity.toUpperCase()} alert`);
    const body = encodeURIComponent(`${a.message}\n\nTime: ${new Date(a.ts).toLocaleString()}\n\nGenerated by AquaPure local dashboard.`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  }

  function onClear() {
    if (!confirm("Clear all alerts?")) return;
    clearAlerts();
    setAlerts([]);
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-3 justify-between">
        <div>
          <h1 className="text-2xl font-semibold flex items-center gap-2">
            <Bell className="h-5 w-5 text-aqua-600" />
            {t.alerts.title}
          </h1>
          <p className="text-sm text-[color:var(--color-muted)] mt-1">{t.alerts.desc}</p>
        </div>
        <div className="flex items-center gap-2">
          <select value={filter} onChange={(e) => setFilter(e.target.value as typeof filter)} className="text-xs px-2 h-8 rounded border border-[color:var(--color-border)] bg-[color:var(--color-card)]">
            <option value="all">All severity</option>
            <option value="marginal">Marginal only</option>
            <option value="critical">Critical only</option>
          </select>
          <button onClick={exportCsv} disabled={alerts.length === 0} className="text-xs px-3 h-8 rounded border border-[color:var(--color-border)] hover:bg-aqua-50 dark:hover:bg-aqua-900/30 inline-flex items-center gap-1.5 disabled:opacity-50">
            <FileDown className="h-3.5 w-3.5" />{t.alerts.exportCsv}
          </button>
          <button onClick={onClear} disabled={alerts.length === 0} className="text-xs px-3 h-8 rounded border border-[color:var(--color-border)] hover:bg-red-50 hover:text-red-700 inline-flex items-center gap-1.5 disabled:opacity-50">
            <Trash2 className="h-3.5 w-3.5" />{t.alerts.clear}
          </button>
        </div>
      </div>

      <div className="rounded-xl border border-[color:var(--color-border)] bg-[color:var(--color-card)] overflow-x-auto">
        {!mounted || alerts.length === 0 ? (
          <div className="p-8 text-center text-sm text-[color:var(--color-muted)]">{t.alerts.noAlerts}</div>
        ) : (
          <table className="w-full text-sm">
            <thead className="text-xs text-[color:var(--color-muted)] bg-aqua-50/40 dark:bg-aqua-900/20">
              <tr>
                <th className="text-left px-4 py-2">{t.alerts.timestamp}</th>
                <th className="text-left px-4 py-2">{t.alerts.severity}</th>
                <th className="text-left px-4 py-2">{t.alerts.sensor}</th>
                <th className="text-left px-4 py-2">{t.alerts.message}</th>
                <th className="text-right px-4 py-2">Share</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((a) => (
                <tr key={a.id} className="border-t border-[color:var(--color-border)]">
                  <td className="px-4 py-2 font-mono text-xs">{new Date(a.ts).toLocaleString()}</td>
                  <td className="px-4 py-2">
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium ${
                      a.severity === "critical" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"
                    }`}>{a.severity}</span>
                  </td>
                  <td className="px-4 py-2 font-medium">{a.sensorId}</td>
                  <td className="px-4 py-2 text-[color:var(--color-muted)]">{a.message}</td>
                  <td className="px-4 py-2 text-right">
                    <button onClick={() => mailto(a)} title="Email" className="p-1 hover:text-aqua-600"><Mail className="h-3.5 w-3.5 inline" /></button>
                    <button onClick={() => shareWA(a)} title="WhatsApp share" className="p-1 hover:text-aqua-600 ml-1"><MessageSquare className="h-3.5 w-3.5 inline" /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
